- hosts: spjenkabitcslp1.bred-it-prod.ad.production.local
  vars:
    tmp_dir: '/tmp'
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
    monthly_date: "{{ lookup('pipe', 'date +%d')}}"
  gather_facts: true

  tasks:
    - name: Remove rman old trace file from other server
      shell: find /home/svc_aiautomate/rman_non-prd_weekly/ -type f -name "weekly_check_rman_*.log" -mmin +240 -delete
      become: true

    - name: Remove old trace file first
      shell: "find /home/svc_aiautomate/ -type f -name summary_non-prd_weekly_check_rman-*.txt -delete"
      become: true

    #
    - name: Summarize logs
      shell: cat $(find  /home/svc_aiautomate/rman_non-prd_weekly/ -type f -name 'weekly_check_rman_*{{date}}.log' | sort  -V) >> /home/svc_aiautomate/summary_non-prd_weekly_check_rman-{{ date }}.txt
      register: summary_log

    - name: Check summary_weekly_check-{{ date }}.txt file
      stat:
        path: '/home/svc_aiautomate/summary_non-prd_weekly_check_rman-{{ date }}.txt'
      register: summaryfile

    - name: Set content mail
      shell: "cat /home/svc_aiautomate/summary_non-prd_weekly_check_rman-{{ date }}.txt"
      register: summary_weekly_rman
      when:
        - summaryfile.stat.exists == true

    - debug: msg="{{ summary_weekly_rman.stdout_lines }}"

    - name: Send mail to DBA
      shell: |
               #EMAIL="pornpoj.mavongwon@bred-it.com"
               EMAIL="support.dba@bred-it.com;goc@bred-it.com"
               CC_EMAIL="mwd.platforms@bred-it.com"
               SUBJECT="[NON-PRD][DBA Weekly Check] DBA Weekly Check Report on {{ date }}"
               BODY='
               <span style="font-size:12px;"><span style="font-family:arial,helvetica,sans-serif;">
               <p>Hi Team,</br>
               <p><span style="font-size:16px"><b> DBA Weekly Check Report on <span style="color:#3633FF"> {{date}} </b></span> </span><br />

               <p><span style="font-size:14px"><b>----- Summary Weekly Check RMAN Backup ----- </b></span></br>

               {{ summary_weekly_rman.stdout }}"

               <p>If have any failed on RMAN backup ,Please contact DBA check on details.</br>
               <p>From</br>
               <p>DBA</br>
               </span></span>
               '
               echo "$BODY" | mutt -e "my_hdr From: Automate NON PRD DBA Weekly check by Jenkins <support.dba@bred-it.com>" -e "set content_type=text/html" -s "$SUBJECT" -- $EMAIL -c $CC_EMAIL
#      delegate_to: "{{ hostvars['spjenkabitcslp1.bred-it-prod.ad.production.local']['ansible_host']}}"
      ignore_errors: true
