- hosts:               spdwhdbcicslp2.bcimr-prod.ad.production.local
  vars:
    env:               'BCIPRODW'
    dump_dir:          '/backup/PRODV14/BCIPRODW/dwh_dump'
    prefix:            'monthly_bidwh_vw_bi_tables_obiee'
  gather_facts:        no
  tasks:
    - name:            Remove old trace file first
      shell:           "find /tmp/* -type f -name monthly_check_expdp_*.log -delete"
      become:          true

    - name:         Copy script
      copy:
       src:         "files/{{ item }}"
       dest:        "/home/svc_aiautomate/{{ item }}"
       mode:        '0755'
       owner:       svc_aiautomate
      with_items:
         - db_mon_expdp_monthly.sh


    - name:            Check expdp DWH backups
      shell:           bash -x /home/svc_aiautomate/db_mon_expdp_monthly.sh {{ env }} {{ dump_dir }} {{ prefix }}
      register:        backup_bciprodw_expdp
      become:          true
#      loop_control:
#             pause: 3
    - debug:           msg="{{ backup_bciprodw_expdp.stdout_lines }}"

#    - debug:           msg="{{item.output}}"
#      with_items:      "{{ backup_html.results | json_query('[].{output: stdout_lines}')}}"


    - name:                      Transfer log To Jenkins
      become_user: svc_aiautomate
      shell: rsync -apvvzhO --no-perms --progress --stats  --rsync-path="sudo rsync"   svc_aiautomate@{{ansible_host}}:/tmp/monthly_check_expdp_*.log  /home/svc_aiautomate/
      delegate_to:   "{{ hostvars['spjenkabitcslp1.bred-it-prod.ad.production.local']['ansible_host']}}"
