- name: find config files
  shell: "cd /etc/httpd/conf.d/; ls -l *{{ BF_NAME }}*conf |awk '{print $9}'"
  register: CONFIG_FILE

- fail:
    msg: "config file for {{ BF_NAME }} does not exists"
  when: CONFIG_FILE == ""

- name: copy template to config files
  template:
    src: template.bankflex.conf.ena.ma.page.j2
    dest: "/etc/httpd/conf.d/{{ CONFIG_FILE.stdout }}"
    owner: root
    group: root
    setype: httpd_config_t
    mode: '0644'
    backup: yes
  register: httpd_result
  notify: "reload httpd"

- name: Debug httpd_result
  debug:
    var: httpd_result
