---
- hosts:                mbkcslsphdbp01.bred-it.local
  vars:
    saphir_backup_dir:  '/backup/mbkbkksphdbp01'
  gather_facts:         no
  tasks:
    - name:            Remove old trace file first
      shell:           "find /tmp/* -type f -name daily_check_*.log -delete"
      become:          true
      ignore_errors: true

    - name:         Copy script
      copy:
       src:         "files/{{ item }}"
       dest:        "/home/svc_aiautomate/{{ item }}"
       mode:        '0755'
       owner:       svc_aiautomate
      with_items:
         - compare_size.sh
         - compare_size_1.sh

    - name:            Check postgres DB backups
      shell:           "/home/svc_aiautomate/compare_size.sh {{ item.path }} {{ item.folder }} {{ item.name }}"
      register:        backup_saphir_mbk
      become:          true
      with_items:
          - { path: "{{saphir_backup_dir}}", folder: saphir_prd, name: "Saphir_MBK_DB" }
          - { path: "{{saphir_backup_dir}}", folder: esb_prd, name: "ESB_MBK_DB" }


    - debug:            msg="{{  item.output}}"
      with_items:       "{{ backup_saphir_mbk.results | json_query('[].{output: stdout_lines}')}}"

    - name:            Check fastpayment DB backups
      shell:           "/home/svc_aiautomate/compare_size_1.sh {{ item.path }} {{ item.folder }} {{ item.name }}"
      register:        backup_fast_mbk
      become:          true
      with_items:
          - { path: "{{saphir_backup_dir}}", folder: fastpayment_prd, name: "FAST_MBK_DB" }


    - debug:            msg="{{  item.output}}"
      with_items:       "{{ backup_fast_mbk.results | json_query('[].{output: stdout_lines}')}}"

    - name:                      Transfer log To Jenkins
      become_user: svc_aiautomate
      shell: rsync -apvvzhO --no-perms --progress --stats  --rsync-path="sudo rsync"   svc_aiautomate@{{ansible_host}}:/tmp/daily_check_*.log  /home/svc_aiautomate/
      delegate_to:   "{{ hostvars['spjenkabitcslp1.bred-it-prod.ad.production.local']['ansible_host']}}"


- hosts:                vuvlisphdbprd1.bredvu.local
  vars:
    saphir_bvl_dir:     '/backup/VUVLISPHDBPRD1.bredvu.local/'
  gather_facts:         no
  tasks:
    - name:            Remove old trace file first
      shell:           "find /tmp/* -type f -name daily_check_*.log -delete"
      become:          true
      ignore_errors: true

    - name:         Copy script
      copy:
       src:         "files/{{ item }}"
       dest:        "/home/svc_aiautomate/{{ item }}"
       mode:        '0755'
       owner:       svc_aiautomate
      with_items:
         - compare_size.sh


    - name:            Check postgres DB backups
      shell:           "/home/svc_aiautomate/compare_size.sh {{ item.path }} {{ item.folder }} {{ item.name }}"
      register:        backup_saphir_bvl
      become:          true
      with_items:
          - { path: "{{saphir_bvl_dir}}", folder: saphir_prd, name: "Saphir_BVL_DB" }
          - { path: "{{saphir_bvl_dir}}", folder: esb_prd, name: "ESB_BVL_DB" }


    - debug:            msg="{{  item.output}}"
      with_items:       "{{ backup_saphir_bvl.results | json_query('[].{output: stdout_lines}')}}"


    - name:                      Transfer log To Jenkins
      become_user: svc_aiautomate
      shell: rsync -apvvzhO --no-perms --progress --stats  --rsync-path="sudo rsync"   svc_aiautomate@{{ansible_host}}:/tmp/daily_check_*.log  /home/svc_aiautomate/
      delegate_to:   "{{ hostvars['spjenkabitcslp1.bred-it-prod.ad.production.local']['ansible_host']}}"
