- hosts:             spjenkabitcslp1.bred-it-prod.ad.production.local
  vars:
    tmp_dir:         '/tmp'
    date:            "{{ lookup('pipe', 'date +%Y%m%d') }}"
    monthly_date:    "{{ lookup('pipe', 'date +%d')}}"
  gather_facts:      no
  tasks:
    - name:          Remove rman old trace file from other server
      shell:         find /home/svc_aiautomate/ -type f -name "daily_check_rman_*$(date --date="1 days ago" +"%Y%m%d").log" -mmin +240 -delete
      become:        true
      ignore_errors: true

    - name:          Remove expdp old trace file from other server
      shell:         find /home/svc_aiautomate/ -type f -name "monthly_check_expdp_*$(date --date="1 days ago" +"%Y%m%d").log" -mmin +240 -delete
      become:        true
      ignore_errors: true

    - name:          Remove old trace file first
      shell:         "find /home/svc_aiautomate/ -type f -name summary_daily_check_rman-*.txt -delete"
      become:        true
      ignore_errors: true
      
    #
    - name:          Summarize logs
      shell:         cat $(find /home/svc_aiautomate/ -maxdepth 1 -type f -name 'daily_check_rman_*{{date}}.log' | sort  -V) >> /home/svc_aiautomate/summary_daily_check_rman-{{ date }}.txt
      register:      summary_log

    # - name:        Summarize logs
    #   shell:       cat /home/svc_aiautomate/daily_check_rman_{{ item }}-*.log >> /home/svc_aiautomate/summary_daily_check_rman-{{ date }}.txt
    #   with_items:
    #      - BBCPRD
    #      - BBFPRD
    #      - BCIMRPRD
    #      - BFLPRD
    #      - BVLPRD
    #      - MBKEDM_DMSDBP
    #      - MBKEDM_CNTDBP
    #      - MBK_SHAREDB_PRD
    #      - MBK_CADDB_PRD
    #      - BBC_CADDB_PRD
    #      - BVL_CADDB_PRD
    #      - BBS_CADDB_PRD
      # register:    summary_log


    - name:          Check summary_daily_check-{{ date }}.txt file
      stat:
        path:        '/home/svc_aiautomate/summary_daily_check_rman-{{ date }}.txt'
      register:      summaryfile


    - name:          Set content mail
      shell:         "cat /home/svc_aiautomate/summary_daily_check_rman-{{ date }}.txt"
      register:      summary_rman
      when:
        - summaryfile.stat.exists == true

    - debug:         msg="{{ summary_rman.stdout_lines }}"

    - name:          Send mail to GOC
      shell:         |
               #EMAIL="sureenart.kietsaroch@bred-it.com"
               EMAIL="support.dba@bred-it.com;goc@bred-it.com"
               CC_EMAIL="applications.integration@bred-it.com"
               SUBJECT="[DBA Daily Check] DBA Daily Check Report on {{ date }}"
               BODY='
               <span style="font-size:12px;"><span style="font-family:arial,helvetica,sans-serif;">
               <p>Hi Team,</br>
               <p><span style="font-size:16px"><b> DBA Daily Check Report on <span style="color:#3633FF"> {{date}} </b></span> </span><br />

               <p><span style="font-size:14px"><b>----- Summary Daily Check RMAN Backup ----- </b></span></br>

               {{ summary_rman.stdout }}"

               <p>If have any failed on RMAN backup ,Please contact DBA check on details.</br>
               <p>From</br>
               <p>DBA</br>
               </span></span>
               '
               echo "$BODY" | mutt -e "my_hdr From: Automate DBA Daily check by Jenkins <support.dba@bred-it.com>" -e "set content_type=text/html" -s "$SUBJECT" -- $EMAIL -c $CC_EMAIL
#      delegate_to:  "{{ hostvars['spjenkabitcslp1.bred-it-prod.ad.production.local']['ansible_host']}}"
      ignore_errors: true
#              If NOK on results,Please contact AI check on details."
